sonar.projectKey=Noahffiliation_Multisearch
sonar.organization=noahffiliation

sonar.sources=.
sonar.tests=tests
sonar.exclusions=tests/**

sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.coverage.exclusions=tests/**, jest.config.js
sonar.cpd.exclusions=tests/**
