name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  node-ci:
    permissions:
      contents: read
      packages: write
      security-events: write
    uses: Noahffiliation/.github/.github/workflows/reusable-node-ci.yml@e75a8cb6da8085a0087798606306a5fab7d0caac
    with:
      node-version: "24.19.0"
      run-build: false
      test-docker: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
