name: 'Dependency Review'

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dependency-review:
    name: Dependency Vulnerability Review
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Run Dependency Review
        uses: actions/dependency-review-action@v4.5.0
        continue-on-error: true
